//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActionType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Domain.Resource.ActionType", typeof(ActionType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاسبه قیمت درخواست.
        /// </summary>
        public static string CalculateRequestCostQuery {
            get {
                return ResourceManager.GetString("CalculateRequestCostQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ حساب سازمان.
        /// </summary>
        public static string ChargeOrganizationStockCommand {
            get {
                return ResourceManager.GetString("ChargeOrganizationStockCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن یک هزینه اکشن .
        /// </summary>
        public static string CreateActionPriceCommand {
            get {
                return ResourceManager.GetString("CreateActionPriceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن جزئیات به یک هزینه اکشن.
        /// </summary>
        public static string CreateActionPriceDetailCommand {
            get {
                return ResourceManager.GetString("CreateActionPriceDetailCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن یک محدودیت درخواست.
        /// </summary>
        public static string CreateLimitRequestCommand {
            get {
                return ResourceManager.GetString("CreateLimitRequestCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن حساب سازمان.
        /// </summary>
        public static string CreateOrganizationStockCommand {
            get {
                return ResourceManager.GetString("CreateOrganizationStockCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف یک هزینه  اکشن.
        /// </summary>
        public static string DeleteActionPriceCommand {
            get {
                return ResourceManager.GetString("DeleteActionPriceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف یک جزئیات هزینه اکشن.
        /// </summary>
        public static string DeleteActionPriceDetailCommand {
            get {
                return ResourceManager.GetString("DeleteActionPriceDetailCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف یک محدودیت درخواست.
        /// </summary>
        public static string DeleteLimitRequestCommand {
            get {
                return ResourceManager.GetString("DeleteLimitRequestCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش هزینه اکشن.
        /// </summary>
        public static string EditActionPriceCommand {
            get {
                return ResourceManager.GetString("EditActionPriceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش محدودیت درخواست.
        /// </summary>
        public static string EditLimitRequestCommand {
            get {
                return ResourceManager.GetString("EditLimitRequestCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش حساب سازمان.
        /// </summary>
        public static string EditOrganizationStockCommand {
            get {
                return ResourceManager.GetString("EditOrganizationStockCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست تاریخچه های فراخوانی.
        /// </summary>
        public static string GetActionHistoryQuery {
            get {
                return ResourceManager.GetString("GetActionHistoryQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست هزینه اکشن ها.
        /// </summary>
        public static string GetAllActionPriceQuery {
            get {
                return ResourceManager.GetString("GetAllActionPriceQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست اشخاص مرتبط با معامله ملکی.
        /// </summary>
        public static string GetAllContractSidesQuery {
            get {
                return ResourceManager.GetString("GetAllContractSidesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست افراد اتباع خارجی.
        /// </summary>
        public static string GetAllForeignPersonInformationQuery {
            get {
                return ResourceManager.GetString("GetAllForeignPersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیستی از اطلاعات اصلی شرکت ها با فیلتر شناسه ملی شرکت های ورودی.
        /// </summary>
        public static string GetAllLegalPersonInformationQuery {
            get {
                return ResourceManager.GetString("GetAllLegalPersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیستی از اعضای شرکت به همراه اطلاعات روزنامه رسمی.
        /// </summary>
        public static string GetAllLegalPersonMemberQuery {
            get {
                return ResourceManager.GetString("GetAllLegalPersonMemberQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست محدودیت درخواست ها.
        /// </summary>
        public static string GetAllLimitRequestQuery {
            get {
                return ResourceManager.GetString("GetAllLimitRequestQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای بررسی صحت ارتباط زوج کدملی ها در سطح مشخص.
        /// </summary>
        public static string GetAllNationalCodeRelationQuery {
            get {
                return ResourceManager.GetString("GetAllNationalCodeRelationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست حساب سازمان ها.
        /// </summary>
        public static string GetAllOrganizationStockQuery {
            get {
                return ResourceManager.GetString("GetAllOrganizationStockQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش همه دسترسی های کاربرجاری.
        /// </summary>
        public static string GetAllPermissionQuery {
            get {
                return ResourceManager.GetString("GetAllPermissionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست دسترسی های یک نقش.
        /// </summary>
        public static string GetAllPermissionsByRoleQuery {
            get {
                return ResourceManager.GetString("GetAllPermissionsByRoleQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیستی از شماره ملی اشخاص با توجه به لیستی از شماره تلفن های ورودی.
        /// </summary>
        public static string GetAllPersonByPhoneNumberQuery {
            get {
                return ResourceManager.GetString("GetAllPersonByPhoneNumberQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیستی از شرکت هایی که شخص در آن عضو می باشد.
        /// </summary>
        public static string GetAllPersonCompanyQuery {
            get {
                return ResourceManager.GetString("GetAllPersonCompanyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیستی از اطلاعات اصلی اشخاص با توجه به لیستی از کدملی اشخاص ورودی.
        /// </summary>
        public static string GetAllRealPersonInformationQuery {
            get {
                return ResourceManager.GetString("GetAllRealPersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نسخه 1دریافت لیست افراد نسبت درجه 1 یا 2.
        /// </summary>
        public static string GetAllRealPersonRelationQuery {
            get {
                return ResourceManager.GetString("GetAllRealPersonRelationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست کل جزییات روابط به همراه شناسه نوع رابطه اصلی.
        /// </summary>
        public static string GetAllRelativeTypeChildQuery {
            get {
                return ResourceManager.GetString("GetAllRelativeTypeChildQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست انواع روابط اصلی.
        /// </summary>
        public static string GetAllRelativeTypeParentQuery {
            get {
                return ResourceManager.GetString("GetAllRelativeTypeParentQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت تمام  نقش های یک دسترسی.
        /// </summary>
        public static string GetAllRolesByPermissionQuery {
            get {
                return ResourceManager.GetString("GetAllRolesByPermissionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیستی از معاملات ملکی یک شخص.
        /// </summary>
        public static string GetContractByIdQuery {
            get {
                return ResourceManager.GetString("GetContractByIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کامل یک معامله ملکی.
        /// </summary>
        public static string GetContractInfoQuery {
            get {
                return ResourceManager.GetString("GetContractInfoQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت کوتاهترین مسیر نوع رابطه بین دو شخص.
        /// </summary>
        public static string GetFamilyRelationGraphQuery {
            get {
                return ResourceManager.GetString("GetFamilyRelationGraphQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت نسبت بین دو شخص.
        /// </summary>
        public static string GetFamilyRelationQuery {
            get {
                return ResourceManager.GetString("GetFamilyRelationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات شهروندی یک تبعه خارجی.
        /// </summary>
        public static string GetForeignPersonInformationQuery {
            get {
                return ResourceManager.GetString("GetForeignPersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات کامل یک آگهی روزنامه رسمی.
        /// </summary>
        public static string GetGazetteInformationQuery {
            get {
                return ResourceManager.GetString("GetGazetteInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست اشخاص یک آگهی روزنامه رسمی.
        /// </summary>
        public static string GetGazettePersonInformationQuery {
            get {
                return ResourceManager.GetString("GetGazettePersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین آپدیت نسب.
        /// </summary>
        public static string GetLatestUpdateDateQuery {
            get {
                return ResourceManager.GetString("GetLatestUpdateDateQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست آگهی های یک شرکت.
        /// </summary>
        public static string GetLegalPersonGazetteQuery {
            get {
                return ResourceManager.GetString("GetLegalPersonGazetteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات اصلی یک شرکت.
        /// </summary>
        public static string GetLegalPersonInformationQuery {
            get {
                return ResourceManager.GetString("GetLegalPersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای بررسی صحت کدملی مدیر یک شرکت.
        /// </summary>
        public static string GetLegalPersonLastManagerQuery {
            get {
                return ResourceManager.GetString("GetLegalPersonLastManagerQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت کدملی شرکت از طریق نام.
        /// </summary>
        public static string GetLegalPersonNationalCodeQuery {
            get {
                return ResourceManager.GetString("GetLegalPersonNationalCodeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات کامل یک وام.
        /// </summary>
        public static string GetLoanFullInformationQuery {
            get {
                return ResourceManager.GetString("GetLoanFullInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست اشخاص یا شرکت های مرتبط با تسهیلات.
        /// </summary>
        public static string GetLoanPersonOfContractQuery {
            get {
                return ResourceManager.GetString("GetLoanPersonOfContractQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست لاگ های اپلیکیشن.
        /// </summary>
        public static string GetLogQuery {
            get {
                return ResourceManager.GetString("GetLogQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیستی از آدرس های شخص یا شرکت.
        /// </summary>
        public static string GetPersonAddressQuery {
            get {
                return ResourceManager.GetString("GetPersonAddressQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیستی از حساب های شخص یا شرکت.
        /// </summary>
        public static string GetPersonBankAccountInformationQuery {
            get {
                return ResourceManager.GetString("GetPersonBankAccountInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت نام کامل شخص بر اساس کدملی.
        /// </summary>
        public static string GetPersonFullNameQuery {
            get {
                return ResourceManager.GetString("GetPersonFullNameQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیستی از تسهیلات بانکی )وام( شخص یا شرکت.
        /// </summary>
        public static string GetPersonLoanInformationQuery {
            get {
                return ResourceManager.GetString("GetPersonLoanInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیستی از تلفن های تماس شخص یا شرکت.
        /// </summary>
        public static string GetPersonPhoneNumberQuery {
            get {
                return ResourceManager.GetString("GetPersonPhoneNumberQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت لیست افراد نسبت درجه 1.
        /// </summary>
        public static string GetRealPersonFamilyRelationQuery {
            get {
                return ResourceManager.GetString("GetRealPersonFamilyRelationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات اصلی یک شخص.
        /// </summary>
        public static string GetRealPersonInformationQuery {
            get {
                return ResourceManager.GetString("GetRealPersonInformationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت کدملی شخص از طریق نام و نام خانوادگی و نام پدر.
        /// </summary>
        public static string GetRealPersonNationalCodeQuery {
            get {
                return ResourceManager.GetString("GetRealPersonNationalCodeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت اطلاعات گراف روابط شخص یا شرکت.
        /// </summary>
        public static string GetRelationQuery {
            get {
                return ResourceManager.GetString("GetRelationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت تعداد کل هزینه ها.
        /// </summary>
        public static string GetTotalCountActionPriceQuery {
            get {
                return ResourceManager.GetString("GetTotalCountActionPriceQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت تعداد کل محدودیت درخواست ها.
        /// </summary>
        public static string GetTotalCountLimitRequestQuery {
            get {
                return ResourceManager.GetString("GetTotalCountLimitRequestQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاسبه آبونمان.
        /// </summary>
        public static string SubscriptionCommand {
            get {
                return ResourceManager.GetString("SubscriptionCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی دسترسی های یک نقش.
        /// </summary>
        public static string UpdateRolePermissionCommand {
            get {
                return ResourceManager.GetString("UpdateRolePermissionCommand", resourceCulture);
            }
        }
    }
}
