//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Display {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Display() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Domain.Resource.Display", typeof(Display).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه جزئیات هزینه.
        /// </summary>
        public static string ActionPriceDetailId {
            get {
                return ResourceManager.GetString("ActionPriceDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه اکشن.
        /// </summary>
        public static string ActionPriceId {
            get {
                return ResourceManager.GetString("ActionPriceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات اشکن ها برای محاسبه قیمت.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اکشن.
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نود/یال.
        /// </summary>
        public static string ActionTypeDetail {
            get {
                return ResourceManager.GetString("ActionTypeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر نوع اکشن.
        /// </summary>
        public static string ActionTypeFilter {
            get {
                return ResourceManager.GetString("ActionTypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه قرارداد.
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد حساب.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمق.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه نوع رابطه ها.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی اول.
        /// </summary>
        public static string FirstNationalCode {
            get {
                return ResourceManager.GetString("FirstNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeDuplicateRequestsHours.
        /// </summary>
        public static string FreeDuplicateRequestsHours {
            get {
                return ResourceManager.GetString("FreeDuplicateRequestsHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر تاریخ از.
        /// </summary>
        public static string FromDateFilter {
            get {
                return ResourceManager.GetString("FromDateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه آگهی.
        /// </summary>
        public static string GazetteId {
            get {
                return ResourceManager.GetString("GazetteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه اکشن.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه تبعه خارجی.
        /// </summary>
        public static string IdentificationNumber {
            get {
                return ResourceManager.GetString("IdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه های اتباع خارجی.
        /// </summary>
        public static string IdentificationNumbers {
            get {
                return ResourceManager.GetString("IdentificationNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ip.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال/غیرفعال بودن حساب.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن باقی مانده حساب به مبلغ حساب جدید.
        /// </summary>
        public static string IsAdded {
            get {
                return ResourceManager.GetString("IsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدود/نامحدود بودن حساب.
        /// </summary>
        public static string IsUnLimit {
            get {
                return ResourceManager.GetString("IsUnLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه شخص حقوقی.
        /// </summary>
        public static string LegalPersonId {
            get {
                return ResourceManager.GetString("LegalPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ملی.
        /// </summary>
        public static string LegalPersonNationalCode {
            get {
                return ResourceManager.GetString("LegalPersonNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدهای ملی.
        /// </summary>
        public static string ListNationalCodeCouple {
            get {
                return ResourceManager.GetString("ListNationalCodeCouple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تا.
        /// </summary>
        public static string MaxDate {
            get {
                return ResourceManager.GetString("MaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر اعتبار منفی.
        /// </summary>
        public static string MaxNegativeCreadit {
            get {
                return ResourceManager.GetString("MaxNegativeCreadit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ از.
        /// </summary>
        public static string MinDate {
            get {
                return ResourceManager.GetString("MinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شخص.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی1.
        /// </summary>
        public static string NationalCode1 {
            get {
                return ResourceManager.GetString("NationalCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی2.
        /// </summary>
        public static string NationalCode2 {
            get {
                return ResourceManager.GetString("NationalCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدهای ملی.
        /// </summary>
        public static string NationalCodes {
            get {
                return ResourceManager.GetString("NationalCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش/عدم نمایش قیمت اکشن.
        /// </summary>
        public static string OnlyCalculateCommandPrice {
            get {
                return ResourceManager.GetString("OnlyCalculateCommandPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه سازمان.
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر شناسه سازمان.
        /// </summary>
        public static string OrganizationIdFilter {
            get {
                return ResourceManager.GetString("OrganizationIdFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه پدر.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبت درصد محدودیت حساب پدر.
        /// </summary>
        public static string ParentRequestPercent {
            get {
                return ResourceManager.GetString("ParentRequestPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه دسترسی.
        /// </summary>
        public static string PermissionId {
            get {
                return ResourceManager.GetString("PermissionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه های دسترسی.
        /// </summary>
        public static string PermissionsId {
            get {
                return ResourceManager.GetString("PermissionsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه سوژه.
        /// </summary>
        public static string PersonId {
            get {
                return ResourceManager.GetString("PersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن ها.
        /// </summary>
        public static string PhoneNumbers {
            get {
                return ResourceManager.GetString("PhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string RealPersonNationalCode {
            get {
                return ResourceManager.GetString("RealPersonNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات اخیر.
        /// </summary>
        public static string RecentHours {
            get {
                return ResourceManager.GetString("RecentHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد درخواست.
        /// </summary>
        public static string RequestCount {
            get {
                return ResourceManager.GetString("RequestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه نقش.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totalCount.
        /// </summary>
        public static string RowCount {
            get {
                return ResourceManager.GetString("RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی دوم.
        /// </summary>
        public static string SecondNationalCode {
            get {
                return ResourceManager.GetString("SecondNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبونمان.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر تا تاریخ.
        /// </summary>
        public static string ToDateFilter {
            get {
                return ResourceManager.GetString("ToDateFilter", resourceCulture);
            }
        }
    }
}
